# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'udeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Auth'



  # Pods for udeApp

end
