# Uncomment the next line to define a global platform for your project
 platform :ios, '16.4'

target 'ders01' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'FirebaseAuth'
pod 'FirebaseFirestore'

  # Pods for ders01

end
